package provision

import (
	"fmt"
	"strings"

	"github.com/Songxwn/Rack-auto/internal/model"
)

func DefaultPartitions(firmware string) []model.Partition {
	if strings.EqualFold(firmware, model.FirmwareBIOS) {
		return []model.Partition{
			{Name: "biosboot", SizeMB: 1, FS: "biosboot", Mount: "", Flags: "bios_grub"},
			{Name: "root", SizeMB: 0, FS: "ext4", Mount: "/", Flags: ""},
		}
	}
	return []model.Partition{
		{Name: "efi", SizeMB: 512, FS: "vfat", Mount: "/boot/efi", Flags: "esp,boot"},
		{Name: "root", SizeMB: 0, FS: "ext4", Mount: "/", Flags: ""},
	}
}

func Validate(parts []model.Partition) error {
	if len(parts) == 0 {
		return fmt.Errorf("至少需要一个分区")
	}
	roots := 0
	for _, p := range parts {
		if p.Mount == "/" {
			roots++
		}
		if p.SizeMB < 0 {
			return fmt.Errorf("分区 %s 大小非法", p.Name)
		}
	}
	if roots != 1 {
		return fmt.Errorf("必须且只能有一个根分区 /")
	}
	return nil
}

func SGDiskScript(device string, parts []model.Partition) []string {
	cmds := []string{
		"wipefs -a " + shellQuote(device),
		"sgdisk --zap-all " + shellQuote(device),
	}
	idx := 1
	for _, p := range parts {
		end := "0"
		if p.SizeMB > 0 {
			end = fmt.Sprintf("+%dM", p.SizeMB)
		}
		typ := "8300"
		switch {
		case strings.Contains(p.Flags, "esp"), p.FS == "vfat" && p.Mount == "/boot/efi":
			typ = "ef00"
		case strings.Contains(p.Flags, "bios_grub"), p.FS == "biosboot":
			typ = "ef02"
		case p.FS == "swap":
			typ = "8200"
		}
		cmds = append(cmds, fmt.Sprintf("sgdisk -n %d:0:%s -t %d:%s -c %d:%s %s", idx, end, idx, typ, idx, p.Name, shellQuote(device)))
		idx++
	}
	cmds = append(cmds, "partprobe "+shellQuote(device), "sleep 2")
	return cmds
}

func FormatCommands(device string, parts []model.Partition) []string {
	var cmds []string
	for i, p := range parts {
		dev := PartitionPath(device, i+1)
		switch p.FS {
		case "vfat", "fat32":
			cmds = append(cmds, "mkfs.vfat -F32 -n "+shellQuote(strings.ToUpper(p.Name))+" "+dev)
		case "ext4":
			cmds = append(cmds, "mkfs.ext4 -F -L "+shellQuote(p.Name)+" "+dev)
		case "xfs":
			cmds = append(cmds, "mkfs.xfs -f -L "+shellQuote(p.Name)+" "+dev)
		case "swap":
			cmds = append(cmds, "mkswap -f "+dev)
		case "biosboot", "":
		default:
			cmds = append(cmds, "mkfs.ext4 -F "+dev)
		}
	}
	return cmds
}

func PartitionPath(disk string, n int) string {
	if strings.Contains(disk, "nvme") || strings.Contains(disk, "mmcblk") || strings.Contains(disk, "loop") {
		return fmt.Sprintf("%sp%d", disk, n)
	}
	return fmt.Sprintf("%s%d", disk, n)
}

func Fstab(parts []model.Partition, device string) string {
	var b strings.Builder
	b.WriteString("# generated by rackauto\n")
	for i, p := range parts {
		if p.Mount == "" && p.FS != "swap" {
			continue
		}
		dev := PartitionPath(device, i+1)
		if p.FS == "swap" {
			fmt.Fprintf(&b, "%s none swap sw 0 0\n", dev)
			continue
		}
		pass := 2
		if p.Mount == "/" {
			pass = 1
		}
		fmt.Fprintf(&b, "%s %s %s defaults 0 %d\n", dev, p.Mount, fsType(p.FS), pass)
	}
	return b.String()
}

func fsType(fs string) string {
	if fs == "fat32" || fs == "vfat" {
		return "vfat"
	}
	return fs
}

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	if strings.IndexFunc(s, func(r rune) bool {
		return r == ' ' || r == '\t' || r == '"' || r == '\'' || r == '$' || r == '`'
	}) == -1 {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}
